#!/bin/bash
# variables:
VAGRANT_VERSION=$(vagrant -v | awk '{print $2}')
VAGRANT_LASTEST="1.6.5"
BOX_NAME="berendt/opensuse-13.1-x86_64"
ZYP_MODULE_DIRECTORY="puppet-manifests/modules/zypprepo"
MYSQL_MODULE_DIRECTORY="puppet-manifests/modules/mysql"
STDLIB_MODULE_DIRECTORY="puppet-manifests/modules/stdlib"
DEFAULT_FILE="puppet-manifests/manifests/default.pp"

# check version and install
if [[ $VAGRANT_VERSION !=  $VAGRANT_LASTEST ]];
  then
    echo "You need to update Vagrant from web site https://www.vagrantup.com/downloads.html up to $VAGRANT_LASTEST version"
  else 
    echo "You have updated version of Vagrant"
fi

# check for correct box
if [[ `vagrant box list | grep $BOX_NAME| awk '{print $1}' ` != $BOX_NAME ]];
  then
    vagrant box add $BOX_NAME
fi

# dirty check of zypprepo module
if [[ ! -d "$ZYP_MODULE_DIRECTORY" ]];
    then
    echo "Downloading zypprepo module"
    git clone https://github.com/deadpoint/puppet-zypprepo.git $ZYP_MODULE_DIRECTORY
fi

if [[  ! -d  "$MYSQL_MODULE_DIRECTORY" ]];
  then
    echo "Downloading mysql module"
    git clone https://github.com/puppetlabs/puppetlabs-mysql.git $MYSQL_MODULE_DIRECTORY
fi

if [[  ! -d  "$STDLIB_MODULE_DIRECTORY" ]];
  then
    echo "Downloading stdlib module"
    git clone https://github.com/puppetlabs/puppetlabs-stdlib.git $STDLIB_MODULE_DIRECTORY
fi

if [[  ! -f  "$DEFAULT_FILE" ]];
  then
    echo "node default { include obs_server }" > $DEFAULT_FILE
    echo "Default node file has been created:"
    cat $DEFAULT_FILE
fi


# startup
echo "Starting vagrant VM"
vagrant up
